version: '3'
services:
  backend:
    container_name: backend
    build:
      context: backend
      args:
        - GIT_REV=${GIT_HASH}
    image: ${REGISTRY_URL}backend-${SUBDOMAIN:-localhost}:${GIT_HASH:-latest}
    restart: 'always'
    env_file: env/backend.env
    command: npm start
    ports:
      - '3000:3000'

  primus:
    container_name: primus
    build: primus
    image: ${REGISTRY_URL}primus-${SUBDOMAIN:-localhost}:${GIT_HASH:-latest}
    restart: 'always'
    env_file: env/primus.env
    command: npm start
    ports:
      - '2333:2333'

  frontend:
    container_name: frontend
    build:
      context: frontend
      args:
        - BUILD_ENV=${BUILD_ENV:-prod}
        - SERVER_NAME=${SERVER_NAME}
        - API_URL=${API_URL:-http://localhost:3000}
        - API_VERSION=${API_VERSION:-api}
        - PRIMUS_URL=${PRIMUS_URL:-http://localhost:2333}
    image: ${REGISTRY_URL}frontend-${SUBDOMAIN:-localhost}:${GIT_HASH:-latest}
    restart: 'always'
    ports:
      - '4200:80'
