version: '3'
services:
  mongodb:
    build: mongodb
    container_name: mongo
    env_file: env/mongodb.env
    ports:
      - 27017:27017

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    env_file: env/rabbitmq.env
    ports:
      - 15672:15672
      - 5672:5672
