# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno and run tests across stable and nightly builds on Windows, Ubuntu and macOS.
# For more information see: https://github.com/denolib/setup-deno

name: Check to build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-image:
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Build applications
        run: docker-compose build

      - name: Build databases
        run: docker-compose -f ./rabbit-mongo.yml build

      - name: Login to container registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com/honeytrap15/sigfox-platform
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Push application packages
        run: docker-compose push

      - name: Push database packages
        run: docker-compose -f ./rabbit-mongo.yml push
